# Generated by Django 3.0.9 on 2020-08-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailentry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailentry',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailentry',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
